// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_-buckEsA3BW45ONFV4hRIXbcKBqd2Fw',
    appId: '1:348313600026:web:6aa6729c8621c59d3991a3',
    messagingSenderId: '348313600026',
    projectId: 'pony-logistics',
    authDomain: 'pony-logistics.firebaseapp.com',
    databaseURL: 'https://pony-logistics-default-rtdb.firebaseio.com',
    storageBucket: 'pony-logistics.appspot.com',
    measurementId: 'G-LEGVJTMJFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg9KXa-uLM-1fe8glR-lAAvq44cq3spPc',
    appId: '1:348313600026:android:814359f4692ab3543991a3',
    messagingSenderId: '348313600026',
    projectId: 'pony-logistics',
    databaseURL: 'https://pony-logistics-default-rtdb.firebaseio.com',
    storageBucket: 'pony-logistics.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5vmEytsl3MqpWvll4rumdFymFRX5ihx4',
    appId: '1:348313600026:ios:8a6a6298013530473991a3',
    messagingSenderId: '348313600026',
    projectId: 'pony-logistics',
    databaseURL: 'https://pony-logistics-default-rtdb.firebaseio.com',
    storageBucket: 'pony-logistics.appspot.com',
    androidClientId: '348313600026-25ja5cjt84b7e1pl78no66pmp92tv94v.apps.googleusercontent.com',
    iosClientId: '348313600026-dei9equplm7jgc8p60v53r6l7tsg18p2.apps.googleusercontent.com',
    iosBundleId: 'com.pony.logistics.ponyLogistics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5vmEytsl3MqpWvll4rumdFymFRX5ihx4',
    appId: '1:348313600026:ios:8a6a6298013530473991a3',
    messagingSenderId: '348313600026',
    projectId: 'pony-logistics',
    databaseURL: 'https://pony-logistics-default-rtdb.firebaseio.com',
    storageBucket: 'pony-logistics.appspot.com',
    androidClientId: '348313600026-25ja5cjt84b7e1pl78no66pmp92tv94v.apps.googleusercontent.com',
    iosClientId: '348313600026-dei9equplm7jgc8p60v53r6l7tsg18p2.apps.googleusercontent.com',
    iosBundleId: 'com.pony.logistics.ponyLogistics',
  );
}
